# Generated by Django 5.2 on 2026-02-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="files/%Y/%m/%d/", verbose_name="file"),
        ),
    ]
